apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: voting
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: wikitops/examplevotingapp-vote:1.0
